### PR TITLE
connect compliant chains

### PR DESCRIPTION
**Pull request by commenthol**
- Rewritten module to obtain fully connect compliance. 
- Backwards compatible interface to version 0.0.1
- Current and new testcases in /test all pass

Please provide me with your feedback.

On accepting, can you please publish on npm?

### CODE REVIEW

**Comment by asalant** [comment]
Thanks for the PR. This is great work.

I have lots of comments about a number of things so I'll start with the highest level one - it seems like there are a few different features/improvements in this PR. I would prefer to be discussing them independently. I think they are:
1. connect compliance - I believe this is the error handling changes
2. chaining with process.nextTick
3. chain.if, chain.switch

Sound right?

I'd love to merge in 1. immediately.

I'd like to discuss 2. as I'm not sure that I like the default behavior in development and production being different. I'd be inclined to have both be synchronous by default and make the async an explicit option.

And for 3., while cool I think it adds complexity for addressing a minority of use cases that could be dealt with fairly simply in other ways. 

I'm sure you don't love the idea of breaking up this work into separate pull requests but I think we'll move forward more quickly if we do.

Thanks!

**Comment by commenthol** [comment]
Hi, thanks for the feedback.

Well breaking up a PR, is quite some work...

Regarding your points:
1. yes - the error handling is in fact what makes the change.
2. The `nextTick` feature is essential to me, as if you think of larger middlewares this could block concurrent requests on the server. The development feature is there because debugging large web-apps can be painful if everything is handled via the event loop. I can live with the default option to be set to `process.nextTick` as this I can influence from outside as well. Would this be an option?  
3. It's 40 lines of additional code, which should not matter that much. The functionality for `chain.if` and `chain.switch` is completely outside the core `chain` functionality. I'am already using this code for a soap-server implementation which helps me to reuse my already existing middlewares without having to rely on `connect`.

**Comment by asalant** [comment]
Okay, I guess we'll discuss these all together...

Re: `process.nextTick`
It doesn't seem right to me to have the default behavior be different that what you would get if you assembled a few connect middleware in a chain with `app.use`. I'd like a developer who is using middleware in series without `connect-chain` to be able to adopt the library as simply as possible without introducing changes to the behavior of their app. I still feel that it's fine to include this as a feature but think that a developer should opt in to it not have it be the default.

I'm not sure running middleware async even needs to be a feature - can't you just do

```
var middleware = function (req, res, next) {
  process.nextTick(function() {
    // do some long running stuff
    next();
  });
}
```

when you need it? It sounds like you need this a lot but I don't feel that is the norm. A long running middleware won't block the app from handling new requests unless it is CPU-bound in the same tick which is going to cause other problems anyway. Or am I missing something?

Re: conditionals
You said "The functionality for chain.if and chain.switch is completely outside the core chain functionality" which actually supports my position that this doesn't seem to belong in the core `connect-chain`. The node philosophy for writing npm modules would encourage us not to write a swiss army knife but to keep the core module simple and focused. What about `connect-chain-conditionals` that mixes `if` and `switch` into `chain` and can be optionally required by a developer who wants these features. We could reference the library from the main `connect-chain` readme.

**Comment by commenthol** [comment]
Hi,
Aggred I have now split the project. Your points should be in there now. Please check and let me know.
Thanks.

**Pull request closed without merging**
